# Generated by Django 5.0.9 on 2024-11-11 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo_de_Datos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='position',
            field=models.TextField(max_length=250, null=True),
        ),
    ]
