# Generated by Django 5.0.9 on 2024-11-12 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo_de_Datos', '0002_pedidos_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cliente', models.TextField(max_length=250)),
                ('name', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Hoja_de_Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Folio_de_Presupuesto', models.TextField(max_length=250)),
                ('Presupuesto', models.TextField(max_length=250)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Modelo_de_Datos.cliente')),
            ],
        ),
    ]
