# Generated by Django 5.0.9 on 2024-11-12 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo_de_Datos', '0004_remove_cliente_id_alter_cliente_id_cliente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoja_de_presupuesto',
            name='id_cliente',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Hoja_de_Presupuesto',
        ),
    ]
