# Generated by Django 5.1.3 on 2024-11-12 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo_de_Datos', '0005_remove_hoja_de_presupuesto_id_cliente_delete_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.TextField(max_length=250)),
                ('nombre', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Hoja_de_Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio_pres', models.TextField(max_length=250)),
                ('presupuesto', models.TextField(max_length=250)),
                ('folio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Modelo_de_Datos.cliente')),
            ],
        ),
    ]
