# Generated by Django 5.1.3 on 2024-11-13 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Modelo_de_Datos', '0007_alter_cliente_folio_alter_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoja_de_presupuesto',
            name='folio',
        ),
        migrations.AddField(
            model_name='hoja_de_presupuesto',
            name='client',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Modelo_de_Datos.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='folio',
            field=models.TextField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.TextField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hoja_de_presupuesto',
            name='folio_pres',
            field=models.TextField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hoja_de_presupuesto',
            name='presupuesto',
            field=models.TextField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
